version: '3'

services:
  html:
    image: unknownty/4640eval-html:latest
    ports:
      - "8080:80"
    environment:
      - API_URL=http://app:5000
      - NGINX_ROOT=/html
    depends_on:
      - app
  app:
    image: unknownty/4640eval-app:latest
    environment:
      - STUDENT_NAME=Tiras Gimpel
      - STUDENT_ID=A01241239
