version: '3'

services:
  html:
    build: html
    ports:
      - "8080:80"
    environment:
      - API_URL=http://app:5000
      - NGINX_ROOT=/html
    depends_on:
      - app
  app:
    build:
      context: app
    environment:
      - STUDENT_NAME=Tiras Gimpel
      - STUDENT_ID=A01241239
