name: docker4640

on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
        -
          name: Checkout the code
          uses: actions/checkout@v3
        -
          name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          name: Build and push backend
          uses: docker/build-push-action@v3
          with:
            context: app
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/4640eval-app:latest
        -
          name: Build and push frontend
          uses: docker/build-push-action@v3
          with:
            context: html
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/4640eval-html:latest